version: '3.4'

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672" # RabbitMQ
    restart: unless-stopped

  heimdalld:
    image: dappnode-polygon_heimdalld:latest
    build:
      args:
        UPSTREAM_VERSION: v0.2.1-mainnet
      context: ./build/heimdall
      dockerfile: Dockerfile
    environment:
      - MONIKER=DAPPNodler
    volumes:
      - heimdall:/root/.heimdalld
    ports:
      - "26656:26656" # P2P
      - "26657:26657" # API
    depends_on:
      - rabbitmq
    environment:
      - moniker=$MONIKER
    command:
      - heimdalld
      - start
      - --moniker=$MONIKER              # Node Identifier
      - --fast_sync                     # Fast blockchain syncing (default true)
      - --p2p.laddr=tcp://0.0.0.0:26656 # p2p listen address
      - --p2p.upnp=false                # Enable/disable UPNP port forwarding
      - --pruning=syncable              # Pruning strategy: syncable, nothing, everything (default "syncable")
      - --rpc.laddr=tcp://0.0.0.0:26657 # RPC listen address
      - --with-tendermint=true          # Run abci app embedded in-process with tendermint (default true)
    restart: unless-stopped

  heimdallr:
    image: dappnode-polygon_heimdalld:latest
    build:
      args:
        UPSTREAM_VERSION: v0.2.1-mainnet
      context: ./build/heimdall
      dockerfile: Dockerfile
    volumes:
      - heimdall:/root/.heimdalld
    ports:
      - "1317:1317" # Heimdall REST
    depends_on:
      - heimdalld
    command:
      - heimdalld
      - rest-server
      - --chain-id=137               # IDK? The chain ID to connect to? 137?
      - --laddr=tcp://0.0.0.0:1317   # The address for the server to listen on (default "tcp://0.0.0.0:1317")
      - --max-open=1000              # The number of maximum open connections (default 1000)
      - --node=tcp://heimdalld:26657 # Address of the node to connect to (default "tcp://localhost:26657")
      - --trust-node=true            # Trust connected full node (don't verify proofs for responses) (default true)
    restart: unless-stopped

  bor:
    build:
      args:
        UPSTREAM_VERSION: v0.2.4
      context: ./build/bor
      dockerfile: Dockerfile
    volumes:
        - bor:/datadir
    ports:
        - "8545:8545" # RPC
        - "30303:30303" # Peers (TCP)
        - "30303:30303/udp" # Peers (UDP)
    depends_on:
      - heimdallr
    command:
        - bor
        - --port=30303
        - --maxpeers=200
        - --datadir=/datadir
        - --networkid=137
        - --miner.gaslimit=200000000
        - --miner.gastarget=20000000
        - --bor.heimdall=http://heimdallr:1317
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --http.api=eth,net,web3,bor
        - --http.corsdomain=*
        - --http.vhosts=*
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=8545
        - --ws.api=eth,net,web3,bor
        - --ws.origins=*
        - --bootnodes=enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303
    restart: unless-stopped

volumes:
  heimdall: {}
  bor: {}
